open! Core
open Towhowcaml
module C = Radatnet.Commands

let c = Radatnet.Core.create ()

let () =
  C.open_file c "/home/errast/code/Touhou7/th07.exe";
  C.analyze_all c LevelThree

let intrinsics = make_intrinsics c
let translate = translate_func c ~intrinsics

let%expect_test _ =
  print_s @@ Mir.Func.sexp_of_t @@ translate 0x47ea7d;
  [%expect {|
    ((name entry0)
     (signature
      ((args (((name ecx) (typ Int)) ((name edx) (typ Int))))
       (return ((name eax) (typ Int)))))
     (blocks
      (((id 0)
        (terminator
         (Branch (succeed (Block 2)) (fail (Block 1)) (condition (Ref 74))))
        (instrs
         ((0 (GetGlobalOp (var esp) (global_name __stack__) (global_type Int)))
          (1 (Const __i32 96)) (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 0)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 1)) (offset 0)))
          (5 (Const __i32 4785824)) (6 (Const __i32 4))
          (7 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 6))))
          (8 (StoreOp (op Store32) (addr (Ref 7)) (value (Ref 5)) (offset 0)))
          (9 (OutsideContext (var ecx) (typ Int)))
          (10 (OutsideContext (var edx) (typ Int))) (11 (Const __i32 4))
          (12 (BiOp (var esp) (op Subtract) (lhs (Ref 7)) (rhs (Ref 11))))
          (13 (Const __i32 4713092))
          (14 (StoreOp (op Store32) (addr (Ref 12)) (value (Ref 13)) (offset 0)))
          (15
           (CallOp (var eax) (func __func480624__) (args ((Ref 9) (Ref 10)))
            (return_type Int)))
          (16 (Const __i32 4713092))
          (17 (LoadOp (var __i32) (op Load32) (addr (Ref 12)) (offset 0)))
          (18 (BiOp (var __i32) (op Equal) (lhs (Ref 17)) (rhs (Ref 16))))
          (19 (AssertOp (condition (Ref 18)))) (20 (Const __i32 4))
          (21 (BiOp (var esp) (op Add) (lhs (Ref 12)) (rhs (Ref 20))))
          (22 (Const __i32 148)) (23 (DupVar (var edi) (src (Ref 22)) (typ Int)))
          (24 (DupVar (var eax) (src (Ref 23)) (typ Int))) (25 (Const __i32 4))
          (26 (BiOp (var esp) (op Subtract) (lhs (Ref 21)) (rhs (Ref 25))))
          (27 (Const __i32 4713104))
          (28 (StoreOp (op Store32) (addr (Ref 26)) (value (Ref 27)) (offset 0)))
          (29
           (CallOp (var eax) (func __func47f3a0__) (args ((Ref 9) (Ref 10)))
            (return_type Int)))
          (30 (Const __i32 4713104))
          (31 (LoadOp (var __i32) (op Load32) (addr (Ref 26)) (offset 0)))
          (32 (BiOp (var __i32) (op Equal) (lhs (Ref 31)) (rhs (Ref 30))))
          (33 (AssertOp (condition (Ref 32)))) (34 (Const __i32 4))
          (35 (BiOp (var esp) (op Add) (lhs (Ref 26)) (rhs (Ref 34))))
          (36 (OutsideContext (var ebp) (typ Int)))
          (37
           (StoreOp (op Store32) (addr (Ref 36)) (value (Ref 35)) (offset -24)))
          (38 (DupVar (var esi) (src (Ref 35)) (typ Int)))
          (39 (StoreOp (op Store32) (addr (Ref 38)) (value (Ref 23)) (offset 0)))
          (40 (Const __i32 4))
          (41 (BiOp (var esp) (op Subtract) (lhs (Ref 35)) (rhs (Ref 40))))
          (42 (StoreOp (op Store32) (addr (Ref 41)) (value (Ref 38)) (offset 0)))
          (43 (Const __i32 4))
          (44 (BiOp (var esp) (op Subtract) (lhs (Ref 41)) (rhs (Ref 43))))
          (45 (Const __i32 4713117))
          (46 (StoreOp (op Store32) (addr (Ref 44)) (value (Ref 45)) (offset 0)))
          (47
           (CallOp (var eax) (func KERNEL32.dll_GetVersionExA)
            (args ((Ref 9) (Ref 10))) (return_type Int)))
          (48 (Const __i32 4713117))
          (49 (LoadOp (var __i32) (op Load32) (addr (Ref 44)) (offset 0)))
          (50 (BiOp (var __i32) (op Equal) (lhs (Ref 49)) (rhs (Ref 48))))
          (51 (AssertOp (condition (Ref 50)))) (52 (Const __i32 4))
          (53 (BiOp (var esp) (op Add) (lhs (Ref 44)) (rhs (Ref 52))))
          (54 (LoadOp (var __i32) (op Load32) (addr (Ref 38)) (offset 16)))
          (55 (DupVar (var ecx) (src (Ref 54)) (typ Int)))
          (56 (Const __i32 4847496))
          (57 (StoreOp (op Store32) (addr (Ref 56)) (value (Ref 55)) (offset 0)))
          (58 (LoadOp (var __i32) (op Load32) (addr (Ref 38)) (offset 4)))
          (59 (DupVar (var eax) (src (Ref 58)) (typ Int)))
          (60 (Const __i32 4847508))
          (61 (StoreOp (op Store32) (addr (Ref 60)) (value (Ref 59)) (offset 0)))
          (62 (LoadOp (var __i32) (op Load32) (addr (Ref 38)) (offset 8)))
          (63 (DupVar (var edx) (src (Ref 62)) (typ Int)))
          (64 (Const __i32 4847512))
          (65 (StoreOp (op Store32) (addr (Ref 64)) (value (Ref 63)) (offset 0)))
          (66 (LoadOp (var __i32) (op Load32) (addr (Ref 38)) (offset 12)))
          (67 (DupVar (var esi) (src (Ref 66)) (typ Int)))
          (68 (Const __i32 32767))
          (69 (BiOp (var __i32) (op And) (lhs (Ref 67)) (rhs (Ref 68))))
          (70 (DupVar (var esi) (src (Ref 69)) (typ Int)))
          (71 (Const __i32 4847500))
          (72 (StoreOp (op Store32) (addr (Ref 71)) (value (Ref 70)) (offset 0)))
          (73 (Const __i32 2))
          (74 (BiOp (var __i32) (op Equal) (lhs (Ref 55)) (rhs (Ref 73))))))
        (roots
         ((Ref 0) (Ref 4) (Ref 8) (Ref 9) (Ref 10) (Ref 14) (Ref 15) (Ref 19)
          (Ref 23) (Ref 28) (Ref 29) (Ref 33) (Ref 36) (Ref 37) (Ref 39)
          (Ref 42) (Ref 46) (Ref 47) (Ref 51) (Ref 53) (Ref 55) (Ref 57)
          (Ref 59) (Ref 61) (Ref 63) (Ref 65) (Ref 70) (Ref 72))))
       ((id 1) (terminator (Goto (Block 2)))
        (instrs
         ((0 (OutsideContext (var esi) (typ Int))) (1 (Const __i32 32768))
          (2 (BiOp (var __i32) (op Or) (lhs (Ref 0)) (rhs (Ref 1))))
          (3 (DupVar (var esi) (src (Ref 2)) (typ Int)))
          (4 (Const __i32 4847500))
          (5 (StoreOp (op Store32) (addr (Ref 4)) (value (Ref 3)) (offset 0)))))
        (roots ((Ref 0) (Ref 3) (Ref 5))))
       ((id 2)
        (terminator
         (Branch (succeed (Block 6)) (fail (Block 3)) (condition (Ref 35))))
        (instrs
         ((0 (OutsideContext (var eax) (typ Int))) (1 (Const __i32 8))
          (2 (UniOp (var __i32) (op SignExtendLow8) (operand (Ref 1))))
          (3 (BiOp (var __i32) (op ShiftLeft) (lhs (Ref 0)) (rhs (Ref 2))))
          (4 (DupVar (var eax) (src (Ref 3)) (typ Int)))
          (5 (OutsideContext (var edx) (typ Int)))
          (6 (BiOp (var __i32) (op Add) (lhs (Ref 4)) (rhs (Ref 5))))
          (7 (DupVar (var eax) (src (Ref 6)) (typ Int)))
          (8 (Const __i32 4847504))
          (9 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 7)) (offset 0)))
          (10 (Const __i32 0)) (11 (DupVar (var esi) (src (Ref 10)) (typ Int)))
          (12 (OutsideContext (var esp) (typ Int))) (13 (Const __i32 4))
          (14 (BiOp (var esp) (op Subtract) (lhs (Ref 12)) (rhs (Ref 13))))
          (15 (StoreOp (op Store32) (addr (Ref 14)) (value (Ref 11)) (offset 0)))
          (16 (Const __i32 4772232))
          (17 (LoadOp (var __i32) (op Load32) (addr (Ref 16)) (offset 0)))
          (18 (DupVar (var edi) (src (Ref 17)) (typ Int)))
          (19 (OutsideContext (var ecx) (typ Int))) (20 (Const __i32 4))
          (21 (BiOp (var esp) (op Subtract) (lhs (Ref 14)) (rhs (Ref 20))))
          (22 (Const __i32 4713200))
          (23 (StoreOp (op Store32) (addr (Ref 21)) (value (Ref 22)) (offset 0)))
          (24
           (CallIndirectOp (var eax) (table_index (Ref 18))
            (args ((Ref 19) (Ref 5))) (return_type Int)))
          (25 (Const __i32 4713200))
          (26 (LoadOp (var __i32) (op Load32) (addr (Ref 21)) (offset 0)))
          (27 (BiOp (var __i32) (op Equal) (lhs (Ref 26)) (rhs (Ref 25))))
          (28 (AssertOp (condition (Ref 27)))) (29 (Const __i32 4))
          (30 (BiOp (var esp) (op Add) (lhs (Ref 21)) (rhs (Ref 29))))
          (31
           (SignedLoadOp (var __i32) (op Load16) (addr (Ref 24)) (signed false)
            (offset 0)))
          (32 (Const __i32 23117))
          (33 (UniOp (var __i32) (op SignExtend16) (operand (Ref 31))))
          (34 (UniOp (var __i32) (op SignExtend16) (operand (Ref 32))))
          (35 (BiOp (var __i32) (op NotEqual) (lhs (Ref 33)) (rhs (Ref 34))))))
        (roots
         ((Ref 0) (Ref 5) (Ref 9) (Ref 11) (Ref 12) (Ref 15) (Ref 18) (Ref 19)
          (Ref 23) (Ref 24) (Ref 28) (Ref 30))))
       ((id 3)
        (terminator
         (Branch (succeed (Block 6)) (fail (Block 4)) (condition (Ref 7))))
        (instrs
         ((0 (OutsideContext (var eax) (typ Int)))
          (1 (LoadOp (var __i32) (op Load32) (addr (Ref 0)) (offset 60)))
          (2 (DupVar (var ecx) (src (Ref 1)) (typ Int)))
          (3 (BiOp (var __i32) (op Add) (lhs (Ref 2)) (rhs (Ref 0))))
          (4 (DupVar (var ecx) (src (Ref 3)) (typ Int)))
          (5 (LoadOp (var __i32) (op Load32) (addr (Ref 4)) (offset 0)))
          (6 (Const __i32 17744))
          (7 (BiOp (var __i32) (op NotEqual) (lhs (Ref 5)) (rhs (Ref 6))))))
        (roots ((Ref 0) (Ref 4))))
       ((id 4)
        (terminator
         (Branch (succeed (Block 9)) (fail (Block 5)) (condition (Ref 5))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1
           (SignedLoadOp (var __i32) (op Load16) (addr (Ref 0)) (signed false)
            (offset 24)))
          (2 (UniOp (var __i32) (op ZeroExtend16) (operand (Ref 1))))
          (3 (DupVar (var eax) (src (Ref 2)) (typ Int))) (4 (Const __i32 267))
          (5 (BiOp (var __i32) (op Equal) (lhs (Ref 3)) (rhs (Ref 4))))))
        (roots ((Ref 0) (Ref 3))))
       ((id 5)
        (terminator
         (Branch (succeed (Block 7)) (fail (Block 6)) (condition (Ref 2))))
        (instrs
         ((0 (OutsideContext (var eax) (typ Int))) (1 (Const __i32 523))
          (2 (BiOp (var __i32) (op Equal) (lhs (Ref 0)) (rhs (Ref 1))))))
        (roots ((Ref 0))))
       ((id 6) (terminator (Goto (Block 12)))
        (instrs
         ((0 (OutsideContext (var esi) (typ Int)))
          (1 (OutsideContext (var ebp) (typ Int)))
          (2 (StoreOp (op Store32) (addr (Ref 1)) (value (Ref 0)) (offset -28)))))
        (roots ((Ref 0) (Ref 1) (Ref 2))))
       ((id 7)
        (terminator
         (Branch (succeed (Block 6)) (fail (Block 8)) (condition (Ref 3))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (LoadOp (var __i32) (op Load32) (addr (Ref 0)) (offset 132)))
          (2 (Const __i32 14))
          (3
           (SignedBiOp (var __i32) (op LessThanEqual) (signed false)
            (lhs (Ref 1)) (rhs (Ref 2))))))
        (roots ((Ref 0))))
       ((id 8) (terminator (Goto (Block 11)))
        (instrs
         ((0 (Const __i32 0)) (1 (DupVar (var eax) (src (Ref 0)) (typ Int)))
          (2 (OutsideContext (var ecx) (typ Int)))
          (3 (LoadOp (var __i32) (op Load32) (addr (Ref 2)) (offset 248)))
          (4 (OutsideContext (var esi) (typ Int)))))
        (roots ((Ref 1) (Ref 2) (Ref 4))))
       ((id 9)
        (terminator
         (Branch (succeed (Block 6)) (fail (Block 10)) (condition (Ref 3))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (LoadOp (var __i32) (op Load32) (addr (Ref 0)) (offset 116)))
          (2 (Const __i32 14))
          (3
           (SignedBiOp (var __i32) (op LessThanEqual) (signed false)
            (lhs (Ref 1)) (rhs (Ref 2))))))
        (roots ((Ref 0))))
       ((id 10) (terminator (Goto (Block 11)))
        (instrs
         ((0 (Const __i32 0)) (1 (DupVar (var eax) (src (Ref 0)) (typ Int)))
          (2 (OutsideContext (var ecx) (typ Int)))
          (3 (LoadOp (var __i32) (op Load32) (addr (Ref 2)) (offset 232)))
          (4 (OutsideContext (var esi) (typ Int)))))
        (roots ((Ref 1) (Ref 2) (Ref 4))))
       ((id 11) (terminator (Goto (Block 12)))
        (instrs
         ((0 (OutsideContext (var __input_compare_arg__) (typ Int)))
          (1 (OutsideContext (var eax) (typ Int)))
          (2 (BiOp (var eax) (op MergeTruncLow8) (lhs (Ref 0)) (rhs (Ref 1))))
          (3 (OutsideContext (var ebp) (typ Int)))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 2)) (offset -28)))))
        (roots ((Ref 0) (Ref 1) (Ref 2) (Ref 3) (Ref 4))))
       ((id 12)
        (terminator
         (Branch (succeed (Block 14)) (fail (Block 13)) (condition (Ref 11))))
        (instrs
         ((0 (Const __i32 1)) (1 (OutsideContext (var esp) (typ Int)))
          (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713286))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func48068a__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713286))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))
          (18 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 19))))
          (21 (DupVar (var ecx) (src (Ref 18)) (typ Int)))))
        (roots
         ((Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15) (Ref 20)
          (Ref 21))))
       ((id 13) (terminator (Goto (Block 14)))
        (instrs
         ((0 (Const __i32 28)) (1 (OutsideContext (var esp) (typ Int)))
          (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713298))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func47ea59__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713298))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))
          (18 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 19))))
          (21 (DupVar (var ecx) (src (Ref 18)) (typ Int)))))
        (roots
         ((Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15) (Ref 20)
          (Ref 21))))
       ((id 14)
        (terminator
         (Branch (succeed (Block 16)) (fail (Block 15)) (condition (Ref 7))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (OutsideContext (var edx) (typ Int))) (2 (Const __i32 4))
          (3 (OutsideContext (var esp) (typ Int)))
          (4 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 2))))
          (5 (Const __i32 4713304))
          (6 (StoreOp (op Store32) (addr (Ref 4)) (value (Ref 5)) (offset 0)))
          (7
           (CallOp (var eax) (func __func481649__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (8 (Const __i32 4713304))
          (9 (LoadOp (var __i32) (op Load32) (addr (Ref 4)) (offset 0)))
          (10 (BiOp (var __i32) (op Equal) (lhs (Ref 9)) (rhs (Ref 8))))
          (11 (AssertOp (condition (Ref 10)))) (12 (Const __i32 4))
          (13 (BiOp (var esp) (op Add) (lhs (Ref 4)) (rhs (Ref 12))))))
        (roots ((Ref 0) (Ref 1) (Ref 3) (Ref 6) (Ref 7) (Ref 11) (Ref 13))))
       ((id 15) (terminator (Goto (Block 16)))
        (instrs
         ((0 (Const __i32 16)) (1 (OutsideContext (var esp) (typ Int)))
          (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713315))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func47ea59__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713315))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))
          (18 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 19))))
          (21 (DupVar (var ecx) (src (Ref 18)) (typ Int)))))
        (roots
         ((Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15) (Ref 20)
          (Ref 21))))
       ((id 16)
        (terminator
         (Branch (succeed (Block 18)) (fail (Block 17)) (condition (Ref 29))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (OutsideContext (var edx) (typ Int))) (2 (Const __i32 4))
          (3 (OutsideContext (var esp) (typ Int)))
          (4 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 2))))
          (5 (Const __i32 4713321))
          (6 (StoreOp (op Store32) (addr (Ref 4)) (value (Ref 5)) (offset 0)))
          (7
           (CallOp (var eax) (func __func483560__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (8 (Const __i32 4713321))
          (9 (LoadOp (var __i32) (op Load32) (addr (Ref 4)) (offset 0)))
          (10 (BiOp (var __i32) (op Equal) (lhs (Ref 9)) (rhs (Ref 8))))
          (11 (AssertOp (condition (Ref 10)))) (12 (Const __i32 4))
          (13 (BiOp (var esp) (op Add) (lhs (Ref 4)) (rhs (Ref 12))))
          (14 (OutsideContext (var esi) (typ Int)))
          (15 (OutsideContext (var ebp) (typ Int)))
          (16
           (StoreOp (op Store32) (addr (Ref 15)) (value (Ref 14)) (offset -4)))
          (17 (Const __i32 4))
          (18 (BiOp (var esp) (op Subtract) (lhs (Ref 13)) (rhs (Ref 17))))
          (19 (Const __i32 4713329))
          (20 (StoreOp (op Store32) (addr (Ref 18)) (value (Ref 19)) (offset 0)))
          (21
           (CallOp (var eax) (func __func483362__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (22 (Const __i32 4713329))
          (23 (LoadOp (var __i32) (op Load32) (addr (Ref 18)) (offset 0)))
          (24 (BiOp (var __i32) (op Equal) (lhs (Ref 23)) (rhs (Ref 22))))
          (25 (AssertOp (condition (Ref 24)))) (26 (Const __i32 4))
          (27 (BiOp (var esp) (op Add) (lhs (Ref 18)) (rhs (Ref 26))))
          (28 (Const __i32 0))
          (29
           (SignedBiOp (var __i32) (op GreaterThanEqual) (signed true)
            (lhs (Ref 21)) (rhs (Ref 28))))))
        (roots
         ((Ref 0) (Ref 1) (Ref 3) (Ref 6) (Ref 7) (Ref 11) (Ref 14) (Ref 15)
          (Ref 16) (Ref 20) (Ref 21) (Ref 25) (Ref 27))))
       ((id 17) (terminator (Goto (Block 18)))
        (instrs
         ((0 (Const __i32 27)) (1 (OutsideContext (var esp) (typ Int)))
          (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713340))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func47ea34__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713340))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))
          (18 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 19))))
          (21 (DupVar (var ecx) (src (Ref 18)) (typ Int)))))
        (roots
         ((Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15) (Ref 20)
          (Ref 21))))
       ((id 18)
        (terminator
         (Branch (succeed (Block 20)) (fail (Block 19)) (condition (Ref 41))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (OutsideContext (var edx) (typ Int))) (2 (Const __i32 4))
          (3 (OutsideContext (var esp) (typ Int)))
          (4 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 2))))
          (5 (Const __i32 4713346))
          (6 (StoreOp (op Store32) (addr (Ref 4)) (value (Ref 5)) (offset 0)))
          (7
           (CallOp (var eax) (func KERNEL32.dll_GetCommandLineA)
            (args ((Ref 0) (Ref 1))) (return_type Int)))
          (8 (Const __i32 4713346))
          (9 (LoadOp (var __i32) (op Load32) (addr (Ref 4)) (offset 0)))
          (10 (BiOp (var __i32) (op Equal) (lhs (Ref 9)) (rhs (Ref 8))))
          (11 (AssertOp (condition (Ref 10)))) (12 (Const __i32 4))
          (13 (BiOp (var esp) (op Add) (lhs (Ref 4)) (rhs (Ref 12))))
          (14 (Const __i32 20337236))
          (15 (StoreOp (op Store32) (addr (Ref 14)) (value (Ref 7)) (offset 0)))
          (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Subtract) (lhs (Ref 13)) (rhs (Ref 16))))
          (18 (Const __i32 4713357))
          (19 (StoreOp (op Store32) (addr (Ref 17)) (value (Ref 18)) (offset 0)))
          (20
           (CallOp (var eax) (func __func483240__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (21 (Const __i32 4713357))
          (22 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (23 (BiOp (var __i32) (op Equal) (lhs (Ref 22)) (rhs (Ref 21))))
          (24 (AssertOp (condition (Ref 23)))) (25 (Const __i32 4))
          (26 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 25))))
          (27 (Const __i32 4847472))
          (28 (StoreOp (op Store32) (addr (Ref 27)) (value (Ref 20)) (offset 0)))
          (29 (Const __i32 4))
          (30 (BiOp (var esp) (op Subtract) (lhs (Ref 26)) (rhs (Ref 29))))
          (31 (Const __i32 4713367))
          (32 (StoreOp (op Store32) (addr (Ref 30)) (value (Ref 31)) (offset 0)))
          (33
           (CallOp (var eax) (func __func48319e__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (34 (Const __i32 4713367))
          (35 (LoadOp (var __i32) (op Load32) (addr (Ref 30)) (offset 0)))
          (36 (BiOp (var __i32) (op Equal) (lhs (Ref 35)) (rhs (Ref 34))))
          (37 (AssertOp (condition (Ref 36)))) (38 (Const __i32 4))
          (39 (BiOp (var esp) (op Add) (lhs (Ref 30)) (rhs (Ref 38))))
          (40 (Const __i32 0))
          (41
           (SignedBiOp (var __i32) (op GreaterThanEqual) (signed true)
            (lhs (Ref 33)) (rhs (Ref 40))))))
        (roots
         ((Ref 0) (Ref 1) (Ref 3) (Ref 6) (Ref 7) (Ref 11) (Ref 15) (Ref 19)
          (Ref 20) (Ref 24) (Ref 28) (Ref 32) (Ref 33) (Ref 37) (Ref 39))))
       ((id 19) (terminator (Goto (Block 20)))
        (instrs
         ((0 (Const __i32 8)) (1 (OutsideContext (var esp) (typ Int)))
          (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713378))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func47ea34__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713378))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))
          (18 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 19))))
          (21 (DupVar (var ecx) (src (Ref 18)) (typ Int)))))
        (roots
         ((Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15) (Ref 20)
          (Ref 21))))
       ((id 20)
        (terminator
         (Branch (succeed (Block 22)) (fail (Block 21)) (condition (Ref 15))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (OutsideContext (var edx) (typ Int))) (2 (Const __i32 4))
          (3 (OutsideContext (var esp) (typ Int)))
          (4 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 2))))
          (5 (Const __i32 4713384))
          (6 (StoreOp (op Store32) (addr (Ref 4)) (value (Ref 5)) (offset 0)))
          (7
           (CallOp (var eax) (func __func482f6b__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (8 (Const __i32 4713384))
          (9 (LoadOp (var __i32) (op Load32) (addr (Ref 4)) (offset 0)))
          (10 (BiOp (var __i32) (op Equal) (lhs (Ref 9)) (rhs (Ref 8))))
          (11 (AssertOp (condition (Ref 10)))) (12 (Const __i32 4))
          (13 (BiOp (var esp) (op Add) (lhs (Ref 4)) (rhs (Ref 12))))
          (14 (Const __i32 0))
          (15
           (SignedBiOp (var __i32) (op GreaterThanEqual) (signed true)
            (lhs (Ref 7)) (rhs (Ref 14))))))
        (roots ((Ref 0) (Ref 1) (Ref 3) (Ref 6) (Ref 7) (Ref 11) (Ref 13))))
       ((id 21) (terminator (Goto (Block 22)))
        (instrs
         ((0 (Const __i32 9)) (1 (OutsideContext (var esp) (typ Int)))
          (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713395))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func47ea34__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713395))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))
          (18 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 19))))
          (21 (DupVar (var ecx) (src (Ref 18)) (typ Int)))))
        (roots
         ((Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15) (Ref 20)
          (Ref 21))))
       ((id 22)
        (terminator
         (Branch (succeed (Block 24)) (fail (Block 23)) (condition (Ref 17))))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (OutsideContext (var edx) (typ Int))) (2 (Const __i32 4))
          (3 (OutsideContext (var esp) (typ Int)))
          (4 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 2))))
          (5 (Const __i32 4713401))
          (6 (StoreOp (op Store32) (addr (Ref 4)) (value (Ref 5)) (offset 0)))
          (7
           (CallOp (var eax) (func __func47f891__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (8 (Const __i32 4713401))
          (9 (LoadOp (var __i32) (op Load32) (addr (Ref 4)) (offset 0)))
          (10 (BiOp (var __i32) (op Equal) (lhs (Ref 9)) (rhs (Ref 8))))
          (11 (AssertOp (condition (Ref 10)))) (12 (Const __i32 4))
          (13 (BiOp (var esp) (op Add) (lhs (Ref 4)) (rhs (Ref 12))))
          (14 (OutsideContext (var ebp) (typ Int)))
          (15
           (StoreOp (op Store32) (addr (Ref 14)) (value (Ref 7)) (offset -32)))
          (16 (OutsideContext (var esi) (typ Int)))
          (17 (BiOp (var __i32) (op Equal) (lhs (Ref 7)) (rhs (Ref 16))))))
        (roots
         ((Ref 0) (Ref 1) (Ref 3) (Ref 6) (Ref 7) (Ref 11) (Ref 13) (Ref 14)
          (Ref 15) (Ref 16))))
       ((id 23) (terminator (Goto (Block 24)))
        (instrs
         ((0 (OutsideContext (var eax) (typ Int)))
          (1 (OutsideContext (var esp) (typ Int))) (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713414))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func47ea34__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713414))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))
          (18 (LoadOp (var __i32) (op Load32) (addr (Ref 17)) (offset 0)))
          (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 17)) (rhs (Ref 19))))
          (21 (DupVar (var ecx) (src (Ref 18)) (typ Int)))))
        (roots
         ((Ref 0) (Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15)
          (Ref 20) (Ref 21))))
       ((id 24)
        (terminator
         (Branch (succeed (Block 26)) (fail (Block 25)) (condition (Ref 38))))
        (instrs
         ((0 (OutsideContext (var esi) (typ Int)))
          (1 (OutsideContext (var ebp) (typ Int)))
          (2 (StoreOp (op Store32) (addr (Ref 1)) (value (Ref 0)) (offset -56)))
          (3 (DupVar (var eax) (src (Ref 1)) (typ Int)))
          (4 (OutsideContext (var esp) (typ Int))) (5 (Const __i32 4))
          (6 (BiOp (var esp) (op Subtract) (lhs (Ref 4)) (rhs (Ref 5))))
          (7 (StoreOp (op Store32) (addr (Ref 6)) (value (Ref 3)) (offset 0)))
          (8 (OutsideContext (var ecx) (typ Int)))
          (9 (OutsideContext (var edx) (typ Int))) (10 (Const __i32 4))
          (11 (BiOp (var esp) (op Subtract) (lhs (Ref 6)) (rhs (Ref 10))))
          (12 (Const __i32 4713427))
          (13 (StoreOp (op Store32) (addr (Ref 11)) (value (Ref 12)) (offset 0)))
          (14
           (CallOp (var eax) (func KERNEL32.dll_GetStartupInfoA)
            (args ((Ref 8) (Ref 9))) (return_type Int)))
          (15 (Const __i32 4713427))
          (16 (LoadOp (var __i32) (op Load32) (addr (Ref 11)) (offset 0)))
          (17 (BiOp (var __i32) (op Equal) (lhs (Ref 16)) (rhs (Ref 15))))
          (18 (AssertOp (condition (Ref 17)))) (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 11)) (rhs (Ref 19))))
          (21 (Const __i32 4))
          (22 (BiOp (var esp) (op Subtract) (lhs (Ref 20)) (rhs (Ref 21))))
          (23 (Const __i32 4713433))
          (24 (StoreOp (op Store32) (addr (Ref 22)) (value (Ref 23)) (offset 0)))
          (25
           (CallOp (var eax) (func __func482f02__) (args ((Ref 8) (Ref 9)))
            (return_type Int)))
          (26 (Const __i32 4713433))
          (27 (LoadOp (var __i32) (op Load32) (addr (Ref 22)) (offset 0)))
          (28 (BiOp (var __i32) (op Equal) (lhs (Ref 27)) (rhs (Ref 26))))
          (29 (AssertOp (condition (Ref 28)))) (30 (Const __i32 4))
          (31 (BiOp (var esp) (op Add) (lhs (Ref 22)) (rhs (Ref 30))))
          (32
           (StoreOp (op Store32) (addr (Ref 1)) (value (Ref 25)) (offset -104)))
          (33
           (SignedLoadOp (var __i32) (op Load8) (addr (Ref 1)) (signed false)
            (offset -56)))
          (34 (Const __i32 1))
          (35 (UniOp (var __i32) (op ZeroExtendLow8) (operand (Ref 33))))
          (36 (UniOp (var __i32) (op ZeroExtendLow8) (operand (Ref 34))))
          (37 (BiOp (var __i32) (op And) (lhs (Ref 35)) (rhs (Ref 36))))
          (38 (UniOp (var __i32) (op EqualsZero) (operand (Ref 37))))))
        (roots
         ((Ref 0) (Ref 1) (Ref 2) (Ref 4) (Ref 7) (Ref 8) (Ref 9) (Ref 13)
          (Ref 14) (Ref 18) (Ref 24) (Ref 25) (Ref 29) (Ref 31) (Ref 32))))
       ((id 25) (terminator (Goto (Block 27)))
        (instrs
         ((0 (OutsideContext (var ebp) (typ Int)))
          (1
           (SignedLoadOp (var __i32) (op Load16) (addr (Ref 0)) (signed false)
            (offset -52)))
          (2 (UniOp (var __i32) (op ZeroExtend16) (operand (Ref 1))))
          (3 (DupVar (var eax) (src (Ref 2)) (typ Int)))))
        (roots ((Ref 0) (Ref 3))))
       ((id 26) (terminator (Goto (Block 27)))
        (instrs
         ((0 (Const __i32 10)) (1 (OutsideContext (var esp) (typ Int)))
          (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (LoadOp (var __i32) (op Load32) (addr (Ref 3)) (offset 0)))
          (6 (Const __i32 4))
          (7 (BiOp (var esp) (op Add) (lhs (Ref 3)) (rhs (Ref 6))))
          (8 (DupVar (var eax) (src (Ref 5)) (typ Int)))))
        (roots ((Ref 1) (Ref 4) (Ref 7) (Ref 8))))
       ((id 27)
        (terminator
         (Branch (succeed (Block 29)) (fail (Block 28)) (condition (Ref 48))))
        (instrs
         ((0 (OutsideContext (var eax) (typ Int)))
          (1 (OutsideContext (var esp) (typ Int))) (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ebp) (typ Int)))
          (6 (LoadOp (var __i32) (op Load32) (addr (Ref 5)) (offset -104)))
          (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 6)) (offset 0)))
          (10 (OutsideContext (var esi) (typ Int))) (11 (Const __i32 4))
          (12 (BiOp (var esp) (op Subtract) (lhs (Ref 8)) (rhs (Ref 11))))
          (13 (StoreOp (op Store32) (addr (Ref 12)) (value (Ref 10)) (offset 0)))
          (14 (Const __i32 4))
          (15 (BiOp (var esp) (op Subtract) (lhs (Ref 12)) (rhs (Ref 14))))
          (16 (StoreOp (op Store32) (addr (Ref 15)) (value (Ref 10)) (offset 0)))
          (17 (OutsideContext (var edi) (typ Int)))
          (18 (OutsideContext (var ecx) (typ Int)))
          (19 (OutsideContext (var edx) (typ Int))) (20 (Const __i32 4))
          (21 (BiOp (var esp) (op Subtract) (lhs (Ref 15)) (rhs (Ref 20))))
          (22 (Const __i32 4713462))
          (23 (StoreOp (op Store32) (addr (Ref 21)) (value (Ref 22)) (offset 0)))
          (24
           (CallIndirectOp (var eax) (table_index (Ref 17))
            (args ((Ref 18) (Ref 19))) (return_type Int)))
          (25 (Const __i32 4713462))
          (26 (LoadOp (var __i32) (op Load32) (addr (Ref 21)) (offset 0)))
          (27 (BiOp (var __i32) (op Equal) (lhs (Ref 26)) (rhs (Ref 25))))
          (28 (AssertOp (condition (Ref 27)))) (29 (Const __i32 4))
          (30 (BiOp (var esp) (op Add) (lhs (Ref 21)) (rhs (Ref 29))))
          (31 (Const __i32 4))
          (32 (BiOp (var esp) (op Subtract) (lhs (Ref 30)) (rhs (Ref 31))))
          (33 (StoreOp (op Store32) (addr (Ref 32)) (value (Ref 24)) (offset 0)))
          (34 (Const __i32 4))
          (35 (BiOp (var esp) (op Subtract) (lhs (Ref 32)) (rhs (Ref 34))))
          (36 (Const __i32 4713465))
          (37 (StoreOp (op Store32) (addr (Ref 35)) (value (Ref 36)) (offset 0)))
          (38
           (CallOp (var eax) (func __func434020__) (args ((Ref 18) (Ref 19)))
            (return_type Int)))
          (39 (Const __i32 4713465))
          (40 (LoadOp (var __i32) (op Load32) (addr (Ref 35)) (offset 0)))
          (41 (BiOp (var __i32) (op Equal) (lhs (Ref 40)) (rhs (Ref 39))))
          (42 (AssertOp (condition (Ref 41)))) (43 (Const __i32 4))
          (44 (BiOp (var esp) (op Add) (lhs (Ref 35)) (rhs (Ref 43))))
          (45 (DupVar (var edi) (src (Ref 38)) (typ Int)))
          (46
           (StoreOp (op Store32) (addr (Ref 5)) (value (Ref 45)) (offset -108)))
          (47 (LoadOp (var __i32) (op Load32) (addr (Ref 5)) (offset -28)))
          (48 (BiOp (var __i32) (op NotEqual) (lhs (Ref 47)) (rhs (Ref 10))))))
        (roots
         ((Ref 0) (Ref 1) (Ref 4) (Ref 5) (Ref 9) (Ref 10) (Ref 13) (Ref 16)
          (Ref 17) (Ref 18) (Ref 19) (Ref 23) (Ref 24) (Ref 28) (Ref 33)
          (Ref 37) (Ref 38) (Ref 42) (Ref 44) (Ref 45) (Ref 46))))
       ((id 28) (terminator (Goto (Block 29)))
        (instrs
         ((0 (OutsideContext (var edi) (typ Int)))
          (1 (OutsideContext (var esp) (typ Int))) (2 (Const __i32 4))
          (3 (BiOp (var esp) (op Subtract) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 3)) (value (Ref 0)) (offset 0)))
          (5 (OutsideContext (var ecx) (typ Int)))
          (6 (OutsideContext (var edx) (typ Int))) (7 (Const __i32 4))
          (8 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 7))))
          (9 (Const __i32 4713481))
          (10 (StoreOp (op Store32) (addr (Ref 8)) (value (Ref 9)) (offset 0)))
          (11
           (CallOp (var eax) (func __func47f9c9__) (args ((Ref 5) (Ref 6)))
            (return_type Int)))
          (12 (Const __i32 4713481))
          (13 (LoadOp (var __i32) (op Load32) (addr (Ref 8)) (offset 0)))
          (14 (BiOp (var __i32) (op Equal) (lhs (Ref 13)) (rhs (Ref 12))))
          (15 (AssertOp (condition (Ref 14)))) (16 (Const __i32 4))
          (17 (BiOp (var esp) (op Add) (lhs (Ref 8)) (rhs (Ref 16))))))
        (roots
         ((Ref 0) (Ref 1) (Ref 4) (Ref 5) (Ref 6) (Ref 10) (Ref 11) (Ref 15)
          (Ref 17))))
       ((id 29) (terminator (Goto (Block 30)))
        (instrs
         ((0 (OutsideContext (var ecx) (typ Int)))
          (1 (OutsideContext (var edx) (typ Int))) (2 (Const __i32 4))
          (3 (OutsideContext (var esp) (typ Int)))
          (4 (BiOp (var esp) (op Subtract) (lhs (Ref 3)) (rhs (Ref 2))))
          (5 (Const __i32 4713486))
          (6 (StoreOp (op Store32) (addr (Ref 4)) (value (Ref 5)) (offset 0)))
          (7
           (CallOp (var eax) (func __func47f9eb__) (args ((Ref 0) (Ref 1)))
            (return_type Int)))
          (8 (Const __i32 4713486))
          (9 (LoadOp (var __i32) (op Load32) (addr (Ref 4)) (offset 0)))
          (10 (BiOp (var __i32) (op Equal) (lhs (Ref 9)) (rhs (Ref 8))))
          (11 (AssertOp (condition (Ref 10)))) (12 (Const __i32 4))
          (13 (BiOp (var esp) (op Add) (lhs (Ref 4)) (rhs (Ref 12))))))
        (roots ((Ref 0) (Ref 1) (Ref 3) (Ref 6) (Ref 7) (Ref 11) (Ref 13))))
       ((id 30) (terminator Return)
        (instrs
         ((0 (OutsideContext (var ebp) (typ Int)))
          (1 (LoadOp (var __i32) (op Load32) (addr (Ref 0)) (offset -4)))
          (2 (Const __i32 4294967295))
          (3 (BiOp (var __i32) (op Or) (lhs (Ref 1)) (rhs (Ref 2))))
          (4 (StoreOp (op Store32) (addr (Ref 0)) (value (Ref 3)) (offset -4)))
          (5 (OutsideContext (var edi) (typ Int)))
          (6 (DupVar (var eax) (src (Ref 5)) (typ Int)))
          (7 (DupVar (var esp) (src (Ref 0)) (typ Int)))
          (8 (OutsideContext (var ecx) (typ Int)))
          (9 (OutsideContext (var edx) (typ Int))) (10 (Const __i32 4))
          (11 (BiOp (var esp) (op Subtract) (lhs (Ref 7)) (rhs (Ref 10))))
          (12 (Const __i32 4713545))
          (13 (StoreOp (op Store32) (addr (Ref 11)) (value (Ref 12)) (offset 0)))
          (14
           (CallOp (var eax) (func __func48065f__) (args ((Ref 8) (Ref 9)))
            (return_type Int)))
          (15 (Const __i32 4713545))
          (16 (LoadOp (var __i32) (op Load32) (addr (Ref 11)) (offset 0)))
          (17 (BiOp (var __i32) (op Equal) (lhs (Ref 16)) (rhs (Ref 15))))
          (18 (AssertOp (condition (Ref 17)))) (19 (Const __i32 4))
          (20 (BiOp (var esp) (op Add) (lhs (Ref 11)) (rhs (Ref 19))))
          (21
           (SetGlobalOp (global_name __stack__) (value (Ref 20))
            (global_type Int)))))
        (roots
         ((Ref 0) (Ref 4) (Ref 5) (Ref 8) (Ref 9) (Ref 13) (Ref 14) (Ref 18)
          (Ref 20) (Ref 21))))))
     (locals
      ((__input_compare_arg__ ((name __input_compare_arg__) (typ Int)))
       (eax ((name eax) (typ Int))) (ebp ((name ebp) (typ Int)))
       (ecx ((name ecx) (typ Int))) (edi ((name edi) (typ Int)))
       (edx ((name edx) (typ Int))) (esi ((name esi) (typ Int)))
       (esp ((name esp) (typ Int)))))) |}]
